name: Lint

on:
  pull_request:
    branches: [main]
    paths: ["**.nix"]
  push:
    branches: [main]
    paths: ["**.nix"]

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035
        with:
          nix_on_tmpfs: true

      - name: Cache Nix store paths
        uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.PK }}

      - name: Check flake evaluation
        run: nix flake check

      - name: Run statix
        run: nix run nixpkgs#statix -- check .

      - name: Run Alejandra
        run: nix run nixpkgs#alejandra --check -- .
