name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - name: Cache Nix builds
        uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5

      - name: Run statix
        run: nix run nixpkgs#statix -- fix

      - name: Run Alejandra
        run: nix run nixpkgs#alejandra -- .

      - name: Commit changes
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto format Nix files
