name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - name: Cache Nix builds
        uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
