name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_on_tmpfs: true

      - name: Cache Nix store paths
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PK }}

      - name: Check flake evaluation
        run: nix flake check

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
          pr-reviewers: zacharyarnaise
          git-author-name: "Zachary Arnaise"
          git-author-email: "121795280+zacharyarnaise@users.noreply.github.com"
          git-committer-name: "Zachary Arnaise"
          git-committer-email: "121795280+zacharyarnaise@users.noreply.github.com"
